# Generated by Django 4.0.3 on 2022-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
