# Generated by Django 4.0.3 on 2022-08-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0005_postmodel_price_postmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
